### ISSUE TITLE
test always failing

### ISSUE THREAD

**Issue by fommil** [propensive/magnolia#125] opened 2018-08-04 12:33 UTC
I don't know  what this is but it always fails for me...

```
[fail]  5cd343  throw on an illegal patch attempt with field type mis...                2.200ms     
                exception thrown during assertion: java.lang.NullPointerException
```

**Comment by joroKr21** [comment] 2018-08-04 13:05
Duplicate of #109

**Closed** 2018-08-04 13:44 UTC
