### ISSUE TITLE
Reduce amount of "ephemeral garbage"

### ISSUE THREAD

**Issue by vpavkin** [propensive/magnolia#114] opened 2018-07-02 06:55 UTC
Title references http://magnolia.work/, no offence intended :)

While testing circe-magnolia on a huge enterprise project, my colleague @mikla faced a "Class file is too large" error during compilation.

There is indeed a file with several hundred codecs derived. With circe-generic it worked (albeit slow), but magnolia seems to generate much more code.
It's a little uncomfortable to realize that you can get such huge amounts of code generated. Reducing the amount of generated code would be really great for magnolia to be used with bigger confidence :)

**Comment by propensive** [comment] 2018-08-08 01:35
This sounds like it must be a huge AST, I managed to construct some of these when I was testing compile-time performance against shapeless, but I got the failure with shapeless first, at which point I stopped experimenting with larger ASTs.

If you could share the AST, it would be interesting to see if it is a bug in Magnolia, or if it's simply too large.

A workaround right now would be to find one or more other nested types occurring in the AST and providing explicit implicit derivations for these in the companion objects for those types. These should be found by Magnolia instead of nesting definitions inside a derivation of the top-level AST type.

In general, it's going to be hard to predict whether a derivation exceeds the maximum classfile size. Each invocation of the macro is aware of itself, but not of other expansions in the same class/object which end up being written to the same classfile, so even if we could predict how big a single expansion is in bytecode terms, the existence of several in the same classfile could still be too big.

You should also try the latest version of Magnolia (v0.9.1, in a couple of hours, hopefully) to see if that works better, as a few things have changed since the version you tried.

I'll leave this ticket open so I can do some checks to try to reduce the amount of code. It might, at the very least, be possible to extract some codegen out into static methods defined elsewhere.

**Comment by joroKr21** [comment] 2018-08-08 05:52
I think there is quite a bit of code generated for throwing errors which could be extracted.

**Comment by bjhartin** [comment] 2019-08-22 23:49
I faced the 'class file too large' error, too.  Upon inspecting the decompiled .class file, I see duplicate typeclass instances.  Perhaps this is normal - I'm not too familiar with macro behaviors.  Here's a minimal reproductive case:

```scala
import scalacheckmagnolia.MagnoliaArbitrary

case class Foo(i: Int)

class MacroTest {
  import MagnoliaArbitrary._

  val result = gen[Foo].arbitrary.sample
  val result2 = gen[Foo].arbitrary.sample
}
```

This results in the following class file (decompiled):

```scala
//decompiled from MacroTest.class

// ...

   private static final Arbitrary fooTypeclass$macro$1$1() {
      Arbitrary paramTypeclass$macro$3 = .MODULE$.arbInt();
      Param[] parameters$macro$4 = new Param[]{magnolia.Magnolia..MODULE$.param("i", paramTypeclass$macro$3, () -> {
         return scala.None..MODULE$;
      }, (x$1) -> {
         return BoxesRunTime.boxToInteger($anonfun$result$2(x$1));
      })};
      return scalacheckmagnolia.MagnoliaArbitrary..MODULE$.combine(magnolia.Magnolia..MODULE$.caseClass("Foo", false, false, parameters$macro$4, (fn$macro$5) -> {
         return new Foo(BoxesRunTime.unboxToInt(fn$macro$5.apply(parameters$macro$4[0])));
      }));
   }

// ...

   private static final Arbitrary fooTypeclass$macro$6$1() {
      Arbitrary paramTypeclass$macro$8 = .MODULE$.arbInt();
      Param[] parameters$macro$9 = new Param[]{magnolia.Magnolia..MODULE$.param("i", paramTypeclass$macro$8, () -> {
         return scala.None..MODULE$;
      }, (x$2) -> {
         return BoxesRunTime.boxToInteger($anonfun$result2$2(x$2));
      })};
      return scalacheckmagnolia.MagnoliaArbitrary..MODULE$.combine(magnolia.Magnolia..MODULE$.caseClass("Foo", false, false, parameters$macro$9, (fn$macro$10) -> {
         return new Foo(BoxesRunTime.unboxToInt(fn$macro$10.apply(parameters$macro$9[0])));
      }));
   }

// ...
```

Isn't that duplicate `Foo` typeclass instances?

**Comment by bjhartin** [comment] 2019-08-23 00:03
If I factor out the `gen[Foo]` calls, it does not duplicate:

```scala
val arbFoo = gen[Foo]

val result = arbFoo.arbitrary.sample
val result2 = arbFoo.arbitrary.sample
```

**Comment by joroKr21** [comment] 2019-08-23 10:54
@bjhartin that's normal. Blackbox macros can't generate code outside of the macro call.

**Comment by joroKr21** [comment] 2020-01-13 01:09
It's hard to tell when exactly it would be ok to close this issue.
This is ongoing effort, but I think that right now there is still a lot of room for improvement.

**Comment by propensive** [comment] 2020-01-20 11:39
I think I missed some of the discussion around here, but if I remember correctly, a few parts of the code were written inline (rather that defined externally, and called) for performance reasons. I did a lot of work with Sam Halliday on this in summer 2018. I'm not sure if the benchmarks still run (I haven't touched them since), but I would be hesitant about changing anything that might result in smaller macro expansions at the expense of runtime performance.

**Closed** 2020-11-10 17:36 UTC
Labels: enhancement
