### ISSUE TITLE
Type alias support

### ISSUE THREAD

**Issue by fokot** [propensive/magnolia#189] opened 2019-12-02 17:01 UTC
This 
```
object XXX extends App {

  import ShowDerivation._

  type CharacterId = Long @@ Character
  case class Character(id: CharacterId, name: String, size: Long)

  implicit val s: Show[String] = new Typeclass[String] {
    override def show(a: String): String = a
  }
  implicit val l: Show[Long] = new Typeclass[Long] {
    override def show(a: Long): String = a.toString
  }

  implicit def t[A, T](implicit show: Show[A]): Show[A @@ T] = show.asInstanceOf[Show[A @@ T]]
//  implicit val sci: Show[CharacterId] = l.asInstanceOf[Show[CharacterId]]

  println(
    implicitly[Show[Character]].show(Character(tag[Character][Long](12), "arg", 123))
  )
}
```
fails with this error
```
Error:scalac: bad qualifier received: mkAttributedQualifier(<notype>, <none>)
```

**Comment by propensive** [comment] 2020-01-02 15:47
Thanks for the clear report! I think there *might* be a solution by adding some explicit dealiasing in the macro, but it would need some experimentation.

**Comment by joroKr21** [comment] 2020-01-12 23:43
Aliasing shapeless' tagged types doesn't work in general (in Scala): scala/bug#10506
I.e. resolving implicits for refined types is unpredictable.
We should fix magnolia to abort early when given a refined type.
It thinks that because `Long with Tag[Character] <: AnyVal` and it's not primitive then it must be a value class 😄

**Comment by joroKr21** [comment] 2020-01-13 00:17
Duplicate of #165 but thanks for the example 👍 
Unfortunately we can't do better than fix the error message, because `t` does not resolve implicitly for the type alias (independent of Magnolia).

**Closed by joroKr21** 2020-01-13 00:17 UTC
Labels: bug, enhancement
